name: travel_itinerary_planner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1 
  # ✅ Firebase dependencies
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2

  # (Optional) Add if you plan to use Firebase Auth later
  # firebase_auth: ^4.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
